---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: verify-deployment
spec:
  workspaces:
    - name: output
  params:
    - name: WORK_DIRECTORY
      description: Directory to start build in (handle multiple branches)
      type: string
    - name: APPLICATION_NAME
      description: Name of the application
      type: string
    - name: TEAM_NAME
      description: Name of the team that doing this exercise :)
      type: string
    - name: DEPLOY_ENVIRONMENT
      description: Environment to deploy the app
      type: string
    - name: VERSION
      description: Version of the application
      type: string  
    - name: PREVIOUS_VERSION
      description: Version of the application
      type: string
    - name: PREVIOUS_CHART_VERSION
      description: Version of currently applied chart
      type: string
  steps:
    - name: verify
      workingDir: $(workspaces.output.path)/$(params.WORK_DIRECTORY)
      image: quay.io/openshift/origin-cli:4.9
      script: |
        #!/bin/sh
        # verify the deployment by checking the VERSION against PREVIOUS_VERSION
        until [ "$label" == "$(params.VERSION)" ]; do
          echo "$(params.APPLICATION_NAME)-$(params.VERSION) version hasn't started to roll out"
          label=$(oc get deployment/$(params.APPLICATION_NAME) -n $(params.TEAM_NAME)-$(params.DEPLOY_ENVIRONMENT) --template='{{ "{{" }} index .metadata.labels "app.kubernetes.io/version" {{ "}}" }}')
          sleep 1
        done
        oc rollout status --timeout=2m deployment/$(params.APPLICATION_NAME) -n $(params.TEAM_NAME)-$(params.DEPLOY_ENVIRONMENT) || rc1=$?
        echo "ROLLOUT_FAIL=$rc1" > rollback
    - name: patch-rollback
      workingDir: $(workspaces.output.path)/$(params.WORK_DIRECTORY)
      image: quay.io/redhat-cop/tekton-task-helm:3.6.3
      script: |
        #!/bin/sh
        source ./rollback
        if [[ $ROLLOUT_FAIL != '' ]]; then
          # TODO - check the roll back has not failed also...
          yq eval -i .applications."$(params.APPLICATION_NAME)".source_ref=\"$(params.PREVIOUS_CHART_VERSION)\"  "$(params.DEPLOY_ENVIRONMENT)/values.yaml"
          yq eval -i .applications."$(params.APPLICATION_NAME)".values.image_version=\"$(params.PREVIOUS_VERSION)\" "$(params.DEPLOY_ENVIRONMENT)/values.yaml"
        else
          echo "No rollback required ğŸ‰ğŸ‰ğŸ‰"
        fi
    - name: commit-changes
      workingDir: $(workspaces.output.path)/$(params.WORK_DIRECTORY)
      image: quay.io/redhat-cop/tekton-task-helm:3.6.3
      script: |
        #!/bin/sh
        source ./rollback
        if [[ $ROLLOUT_FAIL != '' ]]; then
          git config --global user.email "tekton@rht-labs.bot.com"
          git config --global user.name "ğŸˆ Tekton ğŸˆ"
          git config --global push.default simple
          git checkout main
          git add $(params.DEPLOY_ENVIRONMENT)/values.yaml
          git commit -m "ğŸ˜¢ğŸ¤¦ğŸ»â€â™€ï¸ AUTOMATED COMMIT - $(params.APPLICATION_NAME) deployment is reverted to image $(params.PREVIOUS_VERSION) & chart $(params.PREVIOUS_CHART_VERSION) ğŸ˜¢ğŸ¤¦ğŸ»â€â™€ï¸" || rc=$?
          git remote set-url origin $(cat $HOME/.git-credentials)/$(params.TEAM_NAME)/$(params.TEAM_NAME)/tech-exercise.git
          git push -u origin main
          exit $ROLLOUT_FAIL
        else
          echo "$(params.APPLICATION_NAME) v$(params.VERSION) deployment in $(params.DEPLOY_ENVIRONMENT) is successful ğŸ‰ ï¿½"
        fi